import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../app/component/Header"
import Footer from "../app/component/Footer"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <div className="font-Poppins flex flex-col w-full h-screen bg-bg">
          <Header/>
          <div className="w-full flex-1">{children}</div>
          <Footer/>
        </div>
        </body>
    </html>
  );
}
